version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # Listeners: bind to 0.0.0.0 inside container
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      # Advertise the broker address for container-to-container comms
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      # Optional: advertise host address for tools on host if needed:
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      # KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    healthcheck:
      test: ["CMD", "sh", "-c", "echo > /dev/tcp/localhost/9092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6

  api:
    build:
      context: .
      dockerfile: deployment/fastapi/Dockerfile
    image: mc_api:latest
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - ACTIVE_MODEL=LightGBM
      - PYTHONUNBUFFERED=1
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./src/models:/app/src/models
    ports:
      - "8000:8000"

  consumer:
    build:
      context: .
      dockerfile: deployment/consumer/Dockerfile
    image: mc_consumer:latest
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - CONSUMER_MODEL=LightGBM
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_GROUP=campaign_group
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/app/src
      - ./data:/app/data

    ports:
      - "8001:8001"
  producer:
    build:
      context: .
      dockerfile: deployment/producer/Dockerfile
    container_name: producer
    depends_on:
      kafka:
        condition: service_healthy

    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    volumes:
      - ./data:/app/data
    restart: on-failure

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./deployment/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - api
      - consumer

  grafana:
    image: grafana/grafana:9.5.2
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./deployment/grafana-provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
